language: node_js
node_js: stable

install:
  - yarn install

script:
  - hexo generate

after_script:
  - cd ./public
  - git init
  - git config user.name "WillWei"
  - git config user.email "2008weileiming@gmail.com"
  - git add .
  - git commit -m "blog - auto deploy by Travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - source
env:
 global:
   - GH_REF: github.com/weileiming/weileiming.github.io.git
