language: node_js
node_js: stable

before_install:
  - npm install hexo-cli -g

install:
  - npm install

before_script:
    - git config --global user.name 'WillWei'
    - git config --global user.email '2008weileiming@gmail.com'

script:
  - hexo clean
  - hexo generate

#after_script:
#  - cd ./public
#  - git init
#  - git config --global user.name "WillWei"
#  - git config --global user.email "2008weileiming@gmail.com"
#  - git add .
#  - git commit -m "update blog - auto deploy by Travis CI."
#  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

after_success:
    - mkdir .deploy
    - cd .deploy
    - git init
    - git remote add origin $DEPLOY_REPO
    - cp -r ../public/* .
    - git add -A .
    - git commit -m 'Site updated'
    - git push --force --quiet origin master

branches:
  only:
    - source
env:
 global:
   - GH_REF: github.com/weileiming/weileiming.github.io.git
